const $=x=>document.getElementById(x), icons={"コールセンター":"🎧","オフィスワーク":"💻","軽作業・物流":"📦","販売・接客":"🏪","製造・工場":"🏭","医療・介護":"⚕","事務・経理":"¥"};let chosen="";
const cats=[...new Set(JOBS.map(x=>x.cat))];cats.forEach(c=>{let o=document.createElement("option");o.value=c;o.textContent=c;$("cat").appendChild(o)});
$("cats").innerHTML=cats.map(c=>`<button class="cat" data-c="${c}"><i>${icons[c]||"●"}</i><b>${c}</b><small>${JOBS.filter(x=>x.cat===c).length}件</small></button>`).join("");
function search(){let q=$("q").value.toLowerCase(),p=$("place").value.toLowerCase(),c=$("cat").value||chosen,t=$("type").value;return JOBS.filter(j=>(!q||[j.title,j.company,j.area,j.cat,...j.tags].join(" ").toLowerCase().includes(q))&&(!p||j.area.toLowerCase().includes(p))&&(!c||j.cat===c)&&(!t||j.type===t))}
function render(){let a=search();$("count").textContent=`検索結果 ${a.length}件`;$("cards").innerHTML=a.map(j=>`<article class="card" data-id="${j.id}"><div class="pic">${icons[j.cat]||"👤"}</div><div class="body"><h3>${j.title}</h3><div class="meta">${j.company}</div><div class="meta">📍 ${j.area}</div><div class="pay">${j.pay}</div><div class="tags">${j.tags.map(x=>`<span>${x}</span>`).join("")}</div></div></article>`).join("")||"<p>該当する求人がありません。</p>";document.querySelectorAll(".card").forEach(e=>e.onclick=()=>show(+e.dataset.id))}
function show(id){location.href="job-detail.html?id="+id}
$("go").onclick=()=>{chosen="";render();$("jobs").scrollIntoView()};["cat","type"].forEach(x=>$(x).onchange=()=>{chosen="";render()});
document.querySelectorAll("[data-k]").forEach(e=>e.onclick=()=>{let k=e.dataset.k;if(k==="福岡市")$("place").value=k;else $("q").value=k;chosen="";render();$("jobs").scrollIntoView()});
document.querySelectorAll("[data-c]").forEach(e=>e.onclick=()=>{chosen=e.dataset.c;$("cat").value=chosen;render();$("jobs").scrollIntoView()});
function reset(){$("q").value="";$("place").value="";$("cat").value="";$("type").value="";chosen="";render()}$("reset").onclick=$("all").onclick=reset;
$("close").onclick=()=>$("modal").classList.add("hide");$("modal").onclick=e=>{if(e.target===$("modal"))$("modal").classList.add("hide")};render();