const $=x=>document.getElementById(x), ALL_JOBS=[...(typeof HELLOWORK_LIVE_TEST_JOBS!=="undefined"?HELLOWORK_LIVE_TEST_JOBS:[]),...JOBS.map(x=>({...x,source:x.source||"eface"})),...(typeof HELLOWORK_JOBS!=="undefined"?HELLOWORK_JOBS:[])], icons={"コールセンター":"🎧","オフィスワーク":"💻","軽作業・物流":"📦","販売・接客":"🏪","製造・工場":"🏭","医療・介護":"⚕","事務・経理":"¥","営業・セールス":"💼"};let chosen="";
const cats=[...new Set(ALL_JOBS.map(x=>x.cat))];cats.forEach(c=>{let o=document.createElement("option");o.value=c;o.textContent=c;$("cat").appendChild(o)});
$("cats").innerHTML=cats.map(c=>`<button class="cat" data-c="${c}"><i>${icons[c]||"●"}</i><b>${c}</b><small>${ALL_JOBS.filter(x=>x.cat===c).length}件</small></button>`).join("");
function search(){let q=$("q").value.toLowerCase(),p=$("place").value.toLowerCase(),c=$("cat").value||chosen,t=$("type").value;return ALL_JOBS.filter(j=>(!q||[j.title,j.company,j.area,j.cat,...j.tags].join(" ").toLowerCase().includes(q))&&(!p||j.area.toLowerCase().includes(p))&&(!c||j.cat===c)&&(!t||j.type===t))}
function sourceBadge(j){if(j.source==="hellowork-live-test")return '<span class="source-badge hw-live">ハローワーク公開求人・テスト表示</span>';if(j.source==="hellowork-demo")return '<span class="source-badge hw">ハローワーク求人・連携デモ</span>';return '<span class="source-badge eface">E-FACE掲載求人</span>'}
function render(){let a=search();$("count").textContent=`検索結果 ${a.length}件`;$("cards").innerHTML=a.map(j=>`<article class="card" data-id="${j.id}"><div class="pic">${j.image?`<img src="${j.image}" alt="${j.cat}のイメージ画像" loading="lazy">`:(icons[j.cat]||"👤")}</div><div class="body">${sourceBadge(j)}<h3>${j.title}</h3><div class="meta">${j.company}</div><div class="meta">📍 ${j.area}</div><div class="pay">${j.pay}</div><div class="tags">${(j.tags||[]).map(x=>`<span>${x}</span>`).join("")}</div></div></article>`).join("")||"<p>該当する求人がありません。</p>";document.querySelectorAll(".card").forEach(e=>e.onclick=()=>show(e.dataset.id))}
function show(id){location.href="job-detail.html?id="+encodeURIComponent(id)}
$("go").onclick=()=>{chosen="";render();$("jobs").scrollIntoView()};["cat","type"].forEach(x=>$(x).onchange=()=>{chosen="";render()});
document.querySelectorAll("[data-k]").forEach(e=>e.onclick=()=>{let k=e.dataset.k;if(k==="福岡市")$("place").value=k;else $("q").value=k;chosen="";render();$("jobs").scrollIntoView()});
document.querySelectorAll("[data-c]").forEach(e=>e.onclick=()=>{chosen=e.dataset.c;$("cat").value=chosen;render();$("jobs").scrollIntoView()});
function reset(){$("q").value="";$("place").value="";$("cat").value="";$("type").value="";chosen="";render()}$("reset").onclick=$("all").onclick=reset;
$("close").onclick=()=>$("modal").classList.add("hide");$("modal").onclick=e=>{if(e.target===$("modal"))$("modal").classList.add("hide")};render();